server:
  port: 8888
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root